### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by Mrsevic** [wh1t3cAt1k/eslint-config-clean-code#2]
Hello.

After running the linter, I recieve the following error: 

Error: .eslintrc.json » eslint-config-clean-code: Configuration for rule "@typescript-eslint/array-type" is invalid:	Value "array" should be object.    at validateRuleOptions (J:\*\*\node_modules\eslint\lib\shared\config-validator.js:138:19)    at Object.keys.forEach.id (J:\*\*\node_modules\eslint\\node_modules\eslint\lib\shared\config-validator.js:193:9)    at Array.forEach (<anonymous>)    at validateRules 
(J:\*\*\node_modules\eslint\\\lib\shared\config-validator.js:190:30)    at validateConfigArray 
(J:\*\*\node_modules\eslint\\shared\config-validator.js:337:9)    at CascadingConfigArrayFactory._finalizeConfigArray 
(J:\*\*\\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:393:13)    at CascadingConfigArrayFactory.getConfigArrayForFile (J:\*\*\\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:249:21)    at FileEnumerator._iterateFilesWithFile (J:\*\*\node_modules\eslint\lib\cli-engine\file-enumerator.js:323:43)    at FileEnumerator._iterateFiles 
(J:\*\*\node_modules\eslint\lib\cli-engine\file-enumerator.js:304:25)    at FileEnumerator.iterateFiles 
(J:\*\*\node_modules\eslint\lib\cli-engine\file-enumerator.js:256:59)

Any hint would be helpful.

Thanks

**Comment by wh1t3cAt1k** [comment]
Hey, apologies for being inactive here lately. This should be fixed in the latest version. Please feel free to reach out!
