### ISSUE TITLE
Update to Eslint v8

### ISSUE THREAD

**Issue by ChristopherHoffman** [wh1t3cAt1k/eslint-config-clean-code#5]
It would be great to update this package with Eslint 8 compatible versions of dependencies. This still references an old version of `@typescript-esliny/eslint-plugin` that is not Eslint 8 compatible.

Thank you for sharing this ruleset, it drastically simplifies our own config.

**Comment by wh1t3cAt1k** [comment]
@ChristopherHoffman apologies for necroposting, I am not the most responsible OSS maintainer in the world.

This has been updated to 8.0.0 today, latest versions of all plugins - does that work for you?

**Comment by wh1t3cAt1k** [comment]
Closing proactively unless there's additional feedback!
